// <auto-generated />
#nullable enable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaigonWaterbus.Infrastructure.Data;

#nullable disable

namespace SaigonWaterbus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819104500_AddCharterBookingAutoDeleteTrigger")]
    partial class AddCharterBookingAutoDeleteTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // CharterBookingDeletedLogs table
            modelBuilder.Entity("SaigonWaterbus.Infrastructure.Data.Migrations.CharterBookingDeletedLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("BookingCode")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("booking_code");

                    b.Property<DateTime>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DepartureDate")
                        .HasColumnType("date")
                        .HasColumnName("departure_date");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason")
                        .HasDefaultValueSql("'Auto-delete after 12h overdue'::character varying");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("charter_booking_deleted_logs");
                });
#pragma warning restore 612, 618
        }
    }

#nullable enable
    /// <summary>
    /// Entity for charter booking deleted logs table (used by trigger)
    /// </summary>
    public class CharterBookingDeletedLog
    {
        public long Id { get; set; }
        public Guid BookingId { get; set; }
        public string? BookingCode { get; set; }
        public DateOnly? DepartureDate { get; set; }
        public TimeOnly? StartTime { get; set; }
        public DateTime DeletedAt { get; set; }
        public string? Reason { get; set; }
    }
}
