using System.Text.Json.Serialization;
using SaigonWaterbus.Application.Fares;

namespace SaigonWaterbus.Application.Trips;

public sealed record TripSummaryDto(
    Guid TripId,
    string TripCode,
    string RouteName,
    string RouteType,
    DateTimeOffset DepartureTime,
    DateTimeOffset ArrivalTime,
    DateTimeOffset? FromStopScheduledDeparture,
    DateTimeOffset? ToStopScheduledArrival,
    int AvailableSeats,
    int TotalSeats,
    decimal? MinPrice,
    string TripStatus,
    bool IsBookingClosed = false,
    bool IsBookable = true,
    string? BookingClosedReason = null,
    EffectiveFareAdjustmentDto? FareAdjustment = null,
    TripDelayInfoDto? DelayInfo = null,
    DateTimeOffset? AdjustedDepartureTime = null,
    DateTimeOffset? AdjustedArrivalTime = null,
    IReadOnlyList<TripSearchStopDto>? Stops = null);

public sealed record TripSearchStopDto(
    int StopOrder,
    Guid StationId,
    string? StationCode,
    string StationName,
    DateTimeOffset? ScheduledArrival,
    DateTimeOffset? ScheduledDeparture,
    bool IsSelectedFrom,
    bool IsSelectedTo,
    bool IsWithinSelectedSegment);

public sealed record TripDelayInfoDto(
    int DelayMinutes,
    string? DelayReason,
    bool IsDelayActive,
    DateTimeOffset? DelayStartedAt,
    DateTimeOffset? DelayEndedAt,
    int? DelayStartStopOrder,
    int DelayPropagationMinutes);

public sealed record TripDetailDto(
    Guid TripId,
    string TripCode,
    Guid RouteId,
    string RouteName,
    // SellsBySegment: FE hỏi trạm lên/xuống khi true; false = đi nguyên chuyến (ngắm cảnh vòng lặp).
    string RouteType,
    bool SellsBySegment,
    DateTimeOffset DepartureTime,
    DateTimeOffset ArrivalTime,
    int CapacitySnapshot,
    string TripStatus,
    string? StatusNote,
    IReadOnlyList<TripStopDto> Stops,
    string TripType = "Regular",
    Guid? SourceBookingId = null,
    string? SourceBookingCode = null,
    TripBoatDto? Boat = null,
    IReadOnlyList<TripStaffAssignmentDto>? OnBoardStaff = null,
    int TotalPassengerCount = 0,
    string? RouteCode = null,
    TripRouteEndpointDto? FromStation = null,
    TripRouteEndpointDto? ToStation = null,
    int StopCount = 0,
    TripDelayInfoDto? DelayInfo = null,
    DateTimeOffset? AdjustedDepartureTime = null,
    DateTimeOffset? AdjustedArrivalTime = null,
    TripIncidentInfoDto? IncidentInfo = null);

public sealed record TripIncidentInfoDto(
    Guid IncidentId,
    string IncidentType,
    string? Severity,
    string ResolutionStatus,
    DateTimeOffset OccurredAt,
    Guid OriginalBoatId,
    string OriginalBoatName,
    string OriginalBoatCode,
    Guid? RescueBoatId,
    string? RescueBoatName,
    string? RescueBoatCode,
    Guid? ReplacementBoatId,
    string? ReplacementBoatName,
    string? ReplacementBoatCode,
    bool IsTripBoatReplaced,
    string ReplacementMissionType,
    Guid? ReplacementTargetStationId,
    string? ReplacementTargetStationCode,
    string? ReplacementTargetStationName,
    int? ReplacementTargetStopOrder,
    int ReplacementDelayMinutes,
    DateTimeOffset? ReplacementEstimatedResumeAt,
    int ActiveTicketCountSnapshot,
    int OnboardPassengerCountSnapshot,
    int FuturePassengerCountSnapshot,
    string? ReplacementNote,
    DateTimeOffset? RescueDispatchedAt,
    DateTimeOffset? ReplacementAssignedAt,
    DateTimeOffset? ResolvedAt);

public sealed record TripBoatDto(
    Guid VesselId,
    string VesselName,
    [property: JsonIgnore] string VesselCode,
    [property: JsonIgnore] int Capacity,
    [property: JsonIgnore] string Status,
    [property: JsonIgnore] string? ImageUrl = null,
    [property: JsonIgnore] IReadOnlyList<string>? ImageUrls = null,
    [property: JsonIgnore] string? RegistrationNumber = null,
    [property: JsonIgnore] string? ServiceType = null,
    [property: JsonIgnore] int? NumberOfDecks = null,
    [property: JsonIgnore] int? MaxSpeedKmh = null,
    [property: JsonIgnore] int? YearBuilt = null,
    [property: JsonIgnore] string? Description = null);

public sealed record TripRouteEndpointDto(
    Guid StationId,
    [property: JsonIgnore] string StationCode,
    string StationName,
    [property: JsonIgnore] string? ImageUrl,
    [property: JsonIgnore] IReadOnlyList<string> ImageUrls,
    [property: JsonIgnore] string? Address = null,
    [property: JsonIgnore] decimal? Latitude = null,
    [property: JsonIgnore] decimal? Longitude = null,
    [property: JsonIgnore] bool? HasWaitingArea = null,
    [property: JsonIgnore] bool? HasParking = null,
    [property: JsonIgnore] bool? HasTicketCounter = null,
    [property: JsonIgnore] DateTimeOffset? PlannedArrival = null,
    [property: JsonIgnore] DateTimeOffset? PlannedDeparture = null,
    [property: JsonIgnore] DateTimeOffset? AdjustedArrival = null,
    [property: JsonIgnore] DateTimeOffset? AdjustedDeparture = null);

public sealed record TripStaffAssignmentDto(
    Guid AssignmentId,
    Guid StaffUserId,
    string StaffName,
    string? StaffType,
    string AssignmentType,
    DateTimeOffset StartAt,
    DateTimeOffset EndAt,
    string Status,
    string ShiftState,
    string? DutyRole);

public sealed record TripStopDto(
    Guid TripStopId,
    Guid StationId,
    string StationName,
    [property: JsonIgnore] string StationCode,
    int StopOrder,
    DateTimeOffset? ScheduledArrival,
    DateTimeOffset? ScheduledDeparture,
    DateTimeOffset? ActualArrival,
    DateTimeOffset? ActualDeparture,
    string StopStatus,
    int StayDurationMinutes = 0,
    string? Note = null,
    int BoardingPassengerCount = 0,
    IReadOnlyList<TripStaffAssignmentDto>? ScanningStaff = null,
    int AlightingPassengerCount = 0,
    int OnboardPassengerCount = 0,
    int SegmentPassengerCount = 0,
    [property: JsonIgnore] string? StationImageUrl = null,
    [property: JsonIgnore] IReadOnlyList<string>? StationImageUrls = null,
    [property: JsonIgnore] string? StationAddress = null,
    [property: JsonIgnore] decimal? Latitude = null,
    [property: JsonIgnore] decimal? Longitude = null,
    [property: JsonIgnore] bool? HasWaitingArea = null,
    [property: JsonIgnore] bool? HasParking = null,
    [property: JsonIgnore] bool? HasTicketCounter = null,
    DateTimeOffset? PlannedArrival = null,
    DateTimeOffset? PlannedDeparture = null,
    DateTimeOffset? AdjustedArrival = null,
    DateTimeOffset? AdjustedDeparture = null);

public sealed record TripStopPassengerCounts(
    int BoardingPassengerCount,
    int AlightingPassengerCount,
    int OnboardPassengerCount,
    int SegmentPassengerCount);
