<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SaigonWaterbus.Domain</RootNamespace>
    <AssemblyName>SaigonWaterbus.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libphonenumber-csharp" />
    <PackageReference Include="NetTopologySuite" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Entities\Incident.cs" />
  </ItemGroup>

</Project>
